### ISSUE TITLE
CI/CD: format convention (eslint, GH action)

### ISSUE THREAD

**Issue by mefengl** [chatgptjs/chatgpt.js#14]
@adamlui 

Do you have any format config files to share?

I think this issue can be easily solved by asking ChatGPT.

**Comment by adamlui** [comment]
No I didn't configure anything yet, I'm looking at the node.js to npm action though

**Comment by mefengl** [comment]
GH action can be like: 
```yml
name: ESLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

```
